title: High Schooler Blog
email: your-email@example.com
description: "A high schooler's blog for book reviews, articles, and poems."
baseurl: ""
url: "https://your-username.github.io/high-schooler-blog"
theme: jekyll-theme-midnight
github_username: your-username
