source "https://rubygems.org"
gem "jekyll", "~> 4.2.0"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-archives"
gem "jekyll-mentions"
gem "jekyll-gist"
gem "jekyll-redirect-from"
gem "jemoji"
gem "jekyll-relative-links"
gem "jekyll-theme-mediumish"
